cleaned up redirection examples

diff --git a/examples/redirection/exit-status b/examples/redirection/exit-status
--- a/examples/redirection/exit-status
+++ b/examples/redirection/exit-status
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-# run a command that returns a error code
-printf "%v\n"
+printf "Run a command that returns a error code: %s\n" "printf \"\%v\""
+printf "%v"
 
-# exit code for last command $?
+printf "See exit code for last command using: \$?\n"
 echo "\$? =" $?
